-- Enable pgcrypto extension for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Drop enums if they exist
DROP TYPE IF EXISTS USER_ROLE CASCADE;
DROP TYPE IF EXISTS USER_STATUS CASCADE;
DROP TYPE IF EXISTS DEPARTMENT_STATUS CASCADE;
DROP TYPE IF EXISTS ASSET_STATUS CASCADE;
DROP TYPE IF EXISTS ASSET_CONDITION CASCADE;
DROP TYPE IF EXISTS ALLOCATION_STATUS CASCADE;
DROP TYPE IF EXISTS TRANSFER_STATUS CASCADE;
DROP TYPE IF EXISTS BOOKING_STATUS CASCADE;
DROP TYPE IF EXISTS MAINTENANCE_PRIORITY CASCADE;
DROP TYPE IF EXISTS MAINTENANCE_STATUS CASCADE;
DROP TYPE IF EXISTS AUDIT_STATUS CASCADE;
DROP TYPE IF EXISTS VERIFICATION_STATUS CASCADE;
DROP TYPE IF EXISTS NOTIFICATION_TYPE CASCADE;

-- Create enums
CREATE TYPE USER_ROLE AS ENUM ('ADMIN', 'ASSET_MANAGER', 'DEPARTMENT_HEAD', 'EMPLOYEE');
CREATE TYPE USER_STATUS AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE DEPARTMENT_STATUS AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE ASSET_STATUS AS ENUM ('AVAILABLE', 'ALLOCATED', 'RESERVED', 'UNDER_MAINTENANCE', 'LOST', 'RETIRED', 'DISPOSED');
CREATE TYPE ASSET_CONDITION AS ENUM ('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'DAMAGED');
CREATE TYPE ALLOCATION_STATUS AS ENUM ('ACTIVE', 'RETURNED', 'OVERDUE', 'TRANSFERRED');
CREATE TYPE TRANSFER_STATUS AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE BOOKING_STATUS AS ENUM ('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE MAINTENANCE_PRIORITY AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE MAINTENANCE_STATUS AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'TECHNICIAN_ASSIGNED', 'IN_PROGRESS', 'RESOLVED');
CREATE TYPE AUDIT_STATUS AS ENUM ('PLANNED', 'ACTIVE', 'COMPLETED', 'CLOSED');
CREATE TYPE VERIFICATION_STATUS AS ENUM ('VERIFIED', 'MISSING', 'DAMAGED');
CREATE TYPE NOTIFICATION_TYPE AS ENUM ('ALLOCATION', 'BOOKING', 'MAINTENANCE', 'AUDIT', 'TRANSFER', 'REMINDER', 'SYSTEM');
